name: Filter IP Addresses for Country

on:
  schedule:
    - cron: '0 18 * * *' # 每天下午六点 UTC 运行，对应中国时间每天凌晨两点
  workflow_dispatch: # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 启用调试日志
      run: |
        echo "启用 GitHub Actions 调试日志..."
        echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

    - name: 检出代码仓库
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # 确保完整克隆以便于检查变更

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        set -x  # 打开详细日志输出
        echo "开始安装依赖..."
        echo "升级 pip..."
        python -m pip install --upgrade pip 2>&1 | tee pip_upgrade.log
        echo "安装 requests 库..."
        pip install requests 2>&1 | tee pip_install.log
        echo "依赖安装完成。"

    - name: 运行过滤脚本
      run: |
        set -x
        echo "开始运行过滤脚本..."
        python filter_iplist_for_country.py 2>&1 | tee script_output.log
        echo "过滤脚本运行完成。"

    - name: 检查是否有变更
      id: check_changes
      run: |
        set -x
        echo "检查代码仓库是否有变更..."
        git status
        if git diff --quiet; then
          echo "未检测到任何变更。"
          echo "changed=false" >> $GITHUB_ENV
        else
          echo "检测到代码仓库有变更。"
          echo "changed=true" >> $GITHUB_ENV
        fi
      shell: bash

    - name: 提交并推送变更
      if: env.changed == 'true'
      run: |
        set -x
        echo "准备提交并推送变更..."
        echo "将新文件添加到暂存区..."
        git add all_cn.txt all_cn_ipv6.txt delegated-apnic-latest
        echo "配置 Git 用户信息..."
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        echo "创建新的提交..."
        git commit -m "更新 IP 列表"
        echo "推送变更到远程仓库..."
        git push --force origin ${{ github.ref }}
        echo "变更推送成功。"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 日志完成
      run: echo "工作流已成功完成。"
