name: Filter IP Addresses for Country

on:
  schedule:
    - cron: '0 18 * * *' # 每天下午六点 UTC 运行，对应中国时间每天凌晨两点
  workflow_dispatch: # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 启用调试日志
      run: |
        echo "启用 GitHub Actions 调试日志..."
        echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

    - name: 检出代码仓库
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # 确保完整克隆以便于检查变更

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        set -x  # 打开详细日志输出
        echo "开始安装依赖..."
        echo "升级 pip..."
        python -m pip install --upgrade pip
        echo "安装 requests 库..."
        pip install requests
        echo "依赖安装完成。"

    - name: 运行过滤脚本
      run: |
        set -x
        echo "开始运行过滤脚本..."
        python filter_iplist_for_country.py
        echo "过滤脚本运行完成。"
        

    - name: 提交并推送变更
      run: |
        set -x
        echo "准备提交并推送变更..."
        # 仅添加必要的文件
        git add -f all_cn.txt all_cn_ipv6.txt delegated-apnic-latest
        echo "配置 Git 用户信息..."
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        echo "创建新的提交..."
        git commit -m "更新 IP 列表" || echo "没有新的变更需要提交"
        echo "推送变更到远程仓库..."
        git push origin HEAD || echo "没有新的变更需要推送"
        echo "操作完成。"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 日志完成
      run: echo "工作流已成功完成。"
